rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'), # http://<domain>.com/rango/, look at views.py's 'index'
        url(r'^about/', views.about, name='about'),
        url(r'^restricted/', views.restricted, name='restricted'),
        url(r'^add_category/$', views.add_category, name='add_category'),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
        url(r'^search/', views.search, name='search'),
        # The Regex "(?P<category_name_slug>[\w\-]+)" matches any sequences
        # [\w\-]+  <==  one or more character(s) \w and hyphen \-
        # of alphanumeric characters (e.g. a-z, A-Z, or 0-9) and the hyphen(-)
        # before the trailing URL slash "/"
        #url(r'^register/$', views.register, name='register'),
        #url(r'^login/$', views.user_login, name='login'),
        #url(r'^restricted/', views.restricted, name='restricted'),
        #url(r'^logout/$', views.user_logout, name='logout'),
        )

tango_with_django_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.conf import settings

from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self,request, user):
        return '/rango/'
    
    
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tango_with_django_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls', namespace="rango")), #look at module rango's urls.py
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    (r'^accounts/', include('registration.backends.simple.urls',namespace="registration")),
    # 'registration.backend.simple.urls' (1-step process) provides
    #registration -> /accounts/register/
    #registration complete -> /accounts/register/complete
    #login -> /accounts/login/
    #logout -> /accounts/logout/
    #password change -> /password/change/
    #password reset -> /password/reset/
    # for 2-step process, check out 'registration.backends.default.urls'
    # NOTE: 'django-registration-redux' does NOT provide the templates!
    # check 'https://github.com/macdhuibh/django-registration-templates' for some samples
)

# static media file deployment
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile #note User and UserProfile classes are imported from different locations

# a form for the class 'Category'
class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    #specified the widgets that we wish to use for each field to be displayed via 'widget'
    #do not allow user access to property 'view' by 'HiddenInput', yet supplies an 'initial' value of '0' to the model
    #REMEMBER: even if a field is hidden, we have to include it in the form! ...
    #except if a default value is provided in the model
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False) # set this to be not required, because it will be populated by the save() method in themodel

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',) #the 'fields' property specifies fields to be included


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    
    def clean(self):
        """
        Clean user's input URL - append 'http://' in front of the address if necessary
        Override clean() method in ModelForm class.
        """
        cleaned_data = self.cleaned_data # Form data is obtained from the ModelForm dictionary attribute 'cleaned_data'
        url = cleaned_data.get('url') # get the url field - we want to check this

        # If url is not empty and doesn't start with 'http://', prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            
        # We MUST always end the clean() method by returning the reference to the cleaned_data dictionary. 
        # Otherwise we will get some really frustrating errors!
        return cleaned_data
    
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them...
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',) #this specifies fields to be excluded
        #or specify the fields to include (i.e. not include the category field)
        #fields = ('title', 'url', 'views')
    
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput()) 
    #pw is a Charfield, but should be invisible.
    #so a widget=forms.PasswordInput() is used.

    class Meta:
        # describes additional properties about the particular ModelForm class it belongs to
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render

#from django.http import HttpResponse
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm
#from rango.forms import UserForm, UserProfileForm
#from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from rango.bing_search.bing_search import run_query

# Create your views here.

def category(request, category_name_slug):

    # Create a context dictionary which we can pass to the template rendering engine.
    context_dict = {}

    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category_name'] = category.name #add data into context_dict

        # Retrieve all of the associated pages.
        # Note that filter returns >= 1 model instance.
        pages = Page.objects.filter(category=category)

        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
        context_dict['category_name_slug'] = category_name_slug
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything - the template displays the "no category" message for us.
        pass

    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context_dict)

def index(request):
    # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage is the same as {{ boldmessage }} in the template!
    # i.e. render the {{boldmessage}} field etc. in 'index.html' with the values here.
    #context_dict = {'boldmessage': "I am bold font from the context",
    #                'h2_message' : "... And I am another message!"
    #}

    # Query the database for a list of ALL categories currently stored.
    # Order the categories by no. likes in descending order.
    # Retrieve the top 5 only - or all if less than 5.
    # Place the list in our context_dict dictionary which will be passed to the template engine.
    category_list_mostlikes = Category.objects.order_by('-likes')[:5]
    category_list_mostviews = Category.objects.order_by('-views')[:5]
    # query the Category model to retrieve the top five categories (both most liked or viewed).
    # '-' for descending order
    
    context_dict = {'categories_mostlikes': category_list_mostlikes,
                    'categories_mostviews': category_list_mostviews
                    }
    #pass a reference to the list (stored as variable category_list) to the dictionary, context_dict
    
    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.
    return render(request, 'rango/index.html', context_dict) #remember to mention 'context_dict' in here

def about(request):
    #output = r'Rango says here is the about page. <br/> <a href="/rango/">Index</a>'
    #return HttpResponse(output)
    return render(request, 'rango/about.html', {})

@login_required
def add_category(request):
    """
    add_category() view function can handle three different scenarios:
    1. showing a new, blank form for adding a category;
    2. saving form data provided by the user to the associated model, and rendering the Rango homepage; and
    3. if there are errors, redisplay the form with error messages.
    """
    # A HTTP POST? Determine if it was a HTTP GET or POST
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            form.save(commit=True)

            # Now call the index() view.
            # The user will be shown the homepage.
            return index(request)
        else:
            # The supplied form contained errors - just print them to the terminal.
            print(form.errors)
    else:
        # If the request was not a POST, display the form to enter details.
        form = CategoryForm()

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    # Note: the 'category_name_slug' field was passed by the ...(?P<category_name_slug>...) matching field in urls.py
    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        cat = None

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()
                # probably better to use a redirect here.
                #return category(request, category_name_slug)
                # Said and done!
                # Redirect user to the category page
                # To enable the reverse method, I modified the main urls.py to include a namespace 'rango'
                # 'rango:category' calls the 'category' method in 'views.py' in namespace 'rango',
                # with argument 'category_name_slug' as required by the method
                return HttpResponseRedirect(reverse('rango:category', args=(category_name_slug,)))
        else:
            print(form.errors)
    else:
        form = PageForm()

    context_dict = {'form':form, 'category': cat, 'category_name_slug':category_name_slug}

    return render(request, 'rango/add_page.html', context_dict)

"""
def register(request):
    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user # establish a link between the two model instances created

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print user_form.errors, profile_form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request,
            'rango/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered} )
    
def user_login(request):

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
                # We use request.POST.get('<variable>') as opposed to request.POST['<variable>'],
                # because the request.POST.get('<variable>') returns None, if the value does not exist,
                # while the request.POST['<variable>'] will raise key error exception
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.

templates/rango/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}About{% endblock %}

{% block body_block %}
    <div class="page-header">
                <h1>About</h1>
    </div>
    <div>
        <p>This is <strong>Rango's about page.</strong></p>
        <a href="/rango/">Return to Index page</a> <br/> 
        <img src="{% static "images/about_img.jpg" %}" alt="Picture of Sakuya" /> 
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Add Category{% endblock %}

{% block body_block %}
        <form role="form"  id="category_form" method="post" action="/rango/add_category/">
        <h2 class="form-signin-heading">Add a Category</h2>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            </br>
            <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
        </form>
{% endblock %}

templates/rango/add_page.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Add Page{% endblock %}

{% block body_block %}
        {% if category %}
	        <form role="form"  id="page_form" method="post" action="/rango/category/{{category.slug}}/add_page/">
	        <h2 class="form-signin-heading">Add a Page to <a href="/rango/category/{{category.slug}}/"> {{ category.name }}</a></h2>
	            {% csrf_token %}
	            {% for hidden in form.hidden_fields %}
	                {{ hidden }}
	            {% endfor %}
	
	            {% for field in form.visible_fields %}
	                {{ field.errors }}
	                {{ field.help_text }}<br/>
	                {{ field }}<br/>
	            {% endfor %}
	            
	            <br />
	            <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
	        </form>
	    {% else %}
	        The specified category {{ category_name }} does not exist!
        {% endif %}
{% endblock %}

templates/rango/category.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
    <h1>{{ category_name }}</h1>
    {% if category %}
        {% if pages %}
        <ul>
                {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
                </ul>
        {% else %}
                <strong>No pages currently in category.</strong>
                {% endif %}

        {% if user.is_authenticated %}
                {% url 'rango:add_page' category_name_slug as the_url%}
                <a href="{{the_url}}">Add a New Page to {{category_name}}</a>
                {#<a href="/rango/category/{{ category_name_slug }}/add_page/">Add a New Page to {{category_name}}</a>#}
                {% endif %}
        {% else %}
                 The specified category {{ category_name }} does not exist!
    {% endif %}

{% endblock %}

templates/rango/cats.html
{% if cats %}
    <ul class="nav nav-sidebar">
    {% for c in cats %}
        {% if c == act_cat %} <li  class="active" > {% else  %} <li>{% endif %}
        {% url 'rango:category' c.slug as the_url%}
        <a href="{{the_url}}"> {{c.name}} </a></li><br />
    {% endfor %}

{% else %}
    <li> <strong >There are no category present.</strong></li>

    </ul>
{% endif %}

templates/rango/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Index{% endblock %}

    {% block body_block %}
    {% if user.is_authenticated %}
	    <div class="page-header">
	        <h1>Rango says... hello {{ user.username }}!</h1>
	{% else %}
	        <h1>Rango says... hello world!</h1>
	{% endif %}
	    </div>
	    
	<div class="row placeholders">
        <div class="col-xs-12 col-sm-6 placeholder">
        {% if categories_mostlikes %}
        <div class="panel panel-primary">
        <div class="panel-heading">
            </br><h3 class="panel-title"> Most liked categories</h3></br>
        </div>
        </div>
            <ul class="list-group">
                {% for category in categories_mostlikes %}
                <!-- Following line changed to add an HTML hyperlink, display name and link -->
                {#<li><a href="/rango/category/{{ category.slug }}">{{ category.name }}</a></li>#}
                <!-- Use relative path, pass the url template tag the name of the url/view and the slug -->
                {% url 'rango:category' category.slug as the_url%}
                <li class="list-group-item"><a href="{{ the_url }}">{{ category.name }}</a></li>
                
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
        </div>
        <div class="col-xs-12 col-sm-6 placeholder">
        {% if categories_mostviews %}
        <div class="panel panel-primary">
        <div class="panel-heading">
            </br><h3 class="panel-title"> Most viewed categories</h3></br>
        </div>
        </div>
            
            <ul class="list-group">
                {% for category in categories_mostviews %}
                {% url 'rango:category' category.slug as the_url%}
                <li class="list-group-item"><a href="{{ the_url }}">{{ category.name }}</a></li>
                
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
        </div>
    </div>
        <img src="{% static "images/test_img.jpg" %}" alt="Picture of Yuka" /> <!-- New line -->
    {% endblock %}

templates/rango/search.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Search{% endblock %}

{% block body_block %}

    <div class="page-header">
        <h1>Search with Rango</h1>
    </div>

    <div class="row">

        <div class="panel panel-primary">
            <br/>

            <form class="form-inline" id="user_form" method="post" action="{% url 'rango:search' %}">
                {% csrf_token %}
                <!-- Display the search form elements here -->
                <input class="form-control" type="text" size="50" name="query" value="" id="query" />
                <input class="btn btn-primary" type="submit" name="submit" value="Search" />
                <br />
            </form>

            <div class="panel">
                {% if result_list %}
                    <div class="panel-heading">
                    <h3 class="panel-title">Results</h3>
                    <!-- Display search results in an ordered list -->
                    <div class="panel-body">
                        <div class="list-group">
                            {% for result in result_list %}
                                <div class="list-group-item">
                                    <h4 class="list-group-item-heading"><a href="{{ result.link }}">{{ result.title }}</a></h4>
                                    <p class="list-group-item-text">{{ result.summary }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
                </div>
            </div>
 </div>

{% endblock %}